package com.notary.will.enums;

public enum CaseStatus {
    DRAFT, SUBMITTED, UNDER_REVIEW, SUPPLEMENT_REQUIRED, REVIEW_PASSED, REVIEW_FAILED,
    APPOINTMENT_SCHEDULED, INTERVIEWING, WITNESS_SIGNING, ARCHIVED, CLOSED
}
